# Generated by Django 3.2.9 on 2021-11-13 19:21

import apps.sales.utils.enums.recipe_type
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('recipe_type', models.PositiveSmallIntegerField(choices=[(0, 'Bolo'), (1, 'Panettone'), (2, 'EasterEgg'), (3, 'Pie'), (4, 'PartySweet'), (5, 'Default')], default=apps.sales.utils.enums.recipe_type.RecipeType['Default'])),
                ('description', models.CharField(max_length=100, null=True)),
                ('yields', models.PositiveSmallIntegerField(default=1)),
                ('ancillary_recipes', models.ManyToManyField(related_name='ancillary_recipes', to='sales.AuxiliaryRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('item_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recipes', models.ManyToManyField(to='sales.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recipes', models.ManyToManyField(to='sales.SaleRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePackaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging', models.ManyToManyField(to='storage.Packaging')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(to='sales.RecipeIngredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='packagins',
            field=models.ManyToManyField(to='sales.RecipePackaging'),
        ),
        migrations.AddField(
            model_name='auxiliaryrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('recipe_type__in', [0, 1, 2, 3, 4, 5])), name='recipe_recipe_type_valid'),
        ),
    ]
