# Generated by Django 3.2.9 on 2021-11-14 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_amount'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salerecipe',
            name='recipes',
        ),
        migrations.AddField(
            model_name='salerecipe',
            name='discount',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='salerecipe',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salerecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salerecipe',
            name='item_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
        ),
    ]
