# Generated by Django 3.2.9 on 2021-11-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20211114_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
