# Generated by Django 3.2.9 on 2021-11-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20211114_1610'),
        ('sales', '0003_delete_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.pricelist'),
        ),
    ]
