# Generated by Django 3.2.9 on 2021-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salerecipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecipe',
            old_name='item_value',
            new_name='item_price',
        ),
    ]
