# Generated by Django 3.2.9 on 2021-11-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='amount',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
