# Generated by Django 3.2.9 on 2021-11-13 20:49

import apps.recipes.utils.enums.recipe_type
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePackaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging', models.ManyToManyField(to='storage.Packaging')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('recipe_type', models.PositiveSmallIntegerField(choices=[(0, 'Bolo'), (1, 'Panettone'), (2, 'EasterEgg'), (3, 'Pie'), (4, 'PartySweet'), (5, 'Default')], default=apps.recipes.utils.enums.recipe_type.RecipeType['Default'])),
                ('description', models.CharField(max_length=100, null=True)),
                ('yields', models.PositiveSmallIntegerField(default=1)),
                ('ancillary_recipes', models.ManyToManyField(related_name='ancillary_recipes', to='recipes.AuxiliaryRecipe')),
                ('items', models.ManyToManyField(to='recipes.RecipeIngredient')),
                ('packagins', models.ManyToManyField(to='recipes.RecipePackaging')),
            ],
        ),
        migrations.AddField(
            model_name='auxiliaryrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('recipe_type__in', [0, 1, 2, 3, 4, 5])), name='recipe_recipe_type_valid'),
        ),
    ]
