# Generated by Django 3.2.9 on 2021-11-14 00:04

import apps.recipes.utils.enums.recipe_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='packagins',
            new_name='packaging',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cake'), (1, 'Panettone'), (2, 'EasterEgg'), (3, 'Pie'), (4, 'PartySweet'), (5, 'Default')], default=apps.recipes.utils.enums.recipe_type.RecipeType['Default']),
        ),
    ]
