# Generated by Django 3.2.9 on 2021-11-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211113_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='packaging',
        ),
        migrations.AddField(
            model_name='recipe',
            name='packaging',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipepackaging'),
            preserve_default=False,
        ),
    ]
