# Generated by Django 3.2.9 on 2021-11-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='recipe',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe'),
        ),
    ]
